language: node_js
node_js:
    - "5.1"
    - "4"
before_script:
    - npm install -g gulp
    - npm install gulp --save-dev
    - npm install gulp-jshint --save-dev
    - npm install gulp-mocha --save-dev
    - npm install gulp-pandoc --save-dev
script:
    - gulp 
